# Generated by Django 6.0.3 on 2026-03-28 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="system_prompt",
            new_name="instructions",
        ),
    ]
