# Generated by Django 6.0.3 on 2026-04-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='events',
            new_name='history',
        ),
    ]
