# Generated by Django 6.0.3 on 2026-05-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_llmprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="llm_provider",
            field=models.ForeignKey(
                blank=True,
                help_text="LLM provider for this agent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agents.llmprovider",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="Model name to use (must be available in the selected provider)",
                max_length=255,
                null=True,
            ),
        ),
    ]
