# Generated by Django 6.0.3 on 2026-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_llmprovider_help_text"),
        ("documents", "0002_enable_pgvector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="allowed_collections",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collections this agent can search",
                to="documents.collection",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="search_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable document search tool for this agent"
            ),
        ),
    ]
