[tasks]
dev = "process-compose up"
test = "uv run --env-file .env python manage.py test"
migrate = "uv run --env-file .env python manage.py migrate"
mmm = "uv run --env-file .env python manage.py makemigrations && uv run python manage.py migrate"
format = "prek run --all-files"

[tools]
prek = "latest"
process-compose = "latest"
"llama.cpp" = { version = "9090", version_prefix = "b" }
ruff = "latest"
uv = "latest"
