exclude = { glob = "**/migrations/**" }

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v3.2.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.9"

[[repos.hooks]]
id = "ruff-check"
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.3"
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "local"
hooks = [
  { id = "tests", name = "Run tests", entry = "mise run precommit", language = "system", pass_filenames = false, stages = ["commit"] },
]
