# Generated by Django 6.0.3 for mops app
# Merged from agents and documents initial migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # Agent models
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(help_text="Base URL for an OpenAI-compatible HTTP API (include /v1), e.g. http://127.0.0.1:8765/v1")),
                ("available_models", models.JSONField(default=list, help_text="List of available model names")),
                ("last_discovered", models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        "mops.Agent",
                        on_delete=models.CASCADE,
                        related_name="conversations",
                    ),
                ),
            ],
        ),
        # Document models
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/collection_unsorted/")),
                ("name", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(blank=True, help_text="Size in bytes", null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        "mops.Collection",
                        on_delete=models.CASCADE,
                        related_name="documents",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["collection", "created_at"], name="mops_docu_collec_6b4b3a_idx"),
                    models.Index(fields=["id"], name="mops_docu_id_2b4b3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("embedding", models.JSONField(blank=True, default=list, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        "mops.Document",
                        on_delete=models.CASCADE,
                        related_name="chunks",
                    ),
                ),
            ],
            options={
                "ordering": ("document", "chunk_index"),
                "indexes": [
                    models.Index(fields=["document", "chunk_index"], name="mops_docuchunk_docume_6b4b3a_idx"),
                ],
            },
        ),
        # Add search_enabled and allowed_collections to Agent
        migrations.AddField(
            model_name="Agent",
            name="search_enabled",
            field=models.BooleanField(default=False, help_text="Enable document search tool for this agent"),
        ),
        migrations.AddField(
            model_name="Agent",
            name="model_name",
            field=models.CharField(blank=True, help_text="Model name to use (must be available in the selected provider)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="Agent",
            name="llm_provider",
            field=models.ForeignKey(
                "mops.LLMProvider",
                blank=True,
                help_text="LLM provider for this agent",
                null=True,
                on_delete=models.SET_NULL,
            ),
        ),
        migrations.AddField(
            model_name="Agent",
            name="allowed_collections",
            field=models.ManyToManyField(
                "mops.Collection",
                blank=True,
                help_text="Collections this agent can search",
                related_name="agents",
            ),
        ),
    ]
