# Generated by Django 6.0.6 on 2026-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('implementation', models.CharField(help_text='Registered agent factory function name', max_length=255)),
                ('parameters', models.JSONField(default=dict, help_text="Dependency slugs for the agent (e.g., {'prompt': 'my-prompt', 'llm': 'openai'})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tool_slug', models.CharField(help_text="Registered tool factory name (e.g., 'search_documents')", max_length=255)),
                ('parameters', models.JSONField(default=dict, help_text="Runtime parameters for the tool factory (e.g., {'collections': ['docs']})")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='default_model',
            field=models.CharField(blank=True, default='', help_text='Default model to use for this provider', max_length=255),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
