# Generated by Django 6.0.6 on 2026-06-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mops', '0004_migrate_agent_to_code_defined'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='mops.agentconfig'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_conversations', to='mops.agent'),
        ),
    ]
